server:
  port: 8001

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://134.175.102.151/test1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: szmuen_dba
    password: Szmuen@2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: consumer
  servlet:
    multipart:
      max-file-size: 204800000 #200M
      max-request-size: 204800000

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.model
  
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
#feign日志
feign:
  client:
    config:
      provider: 
        logger-level: full
logging:
  level:
    com.cosume.feign.UserFeignClient: debug



